# ===================================================================
#
# Markdown lint file
#
# ===================================================================

# First heading should be a top level heading
MD002: false

# Heading Style
MD003:
  style: "atx"

# Line length
MD013: false

# Inline HTML
MD033: false

# MkDocs requires 4 spaces to indent nested list items
MD007:
  indent: 4

# Properly numbered ordered lists
MD029:
  style: ordered

# Code block style
MD046: false
