os: linux
dist: xenial
language: shell
jobs:
  include:
    - stage: lint
      language: node_js
      node_js:
        - 14
      install:
        - npm install -g npm@8.16.0
        - npm install -g markdownlint-cli@0.32.1
      script:
        - markdownlint **/*.md
    - stage: lint
      language: node_js
      node_js:
        - 14
      install:
        - npm install -g npm@8.16.0
        - npm install -g markdown-link-check@3.10.2
      script:
        - for file in  $(find ./content -name \*.md); do markdown-link-check --config .markdown-link-check.json --verbose "$file" || exit 1; done;
    - stage: build
      language: python
      python:
        - 3.6
      install:
        - python -m pip install --upgrade pip
        - python -m pip install -r requirements.txt
      script:
        - make publish
      deploy:
        provider: pages
        skip_cleanup: true
        strategy: git
        token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: output
        on:
          branch: master
